# Generated by Django 5.2.1 on 2025-05-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
