# Generated by Django 5.2.1 on 2025-05-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anonymoususer_is_active_anonymoususer_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='exchange_code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='password_hash',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='actor_token',
            field=models.CharField(blank=True, default='unknown', help_text='HMAC-SHA256(actor_identity)', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='details_enc',
            field=models.TextField(blank=True, default='', help_text='AEAD-encrypted JSON'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='ip_hmac',
            field=models.CharField(blank=True, default='', help_text='HMAC-SHA256(ip_address)', max_length=64),
            preserve_default=False,
        ),
    ]
