# Generated by Django 5.2.1 on 2025-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securityquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='success_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
