# Generated by Django 5.2.1 on 2025-06-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_initial'),
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2plisting',
            name='escrow_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrow.escrowwallet'),
        ),
    ]
