# Generated by Django 5.2.1 on 2025-05-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedispute',
            name='evidence_ipfs_cid',
            field=models.CharField(blank=True, help_text='IPFS CID for encrypted evidence bundle', max_length=64, null=True),
        ),
    ]
